/** Directed slug-token → search aliases (one-way; never reverse). */
export const KEYWORD_ALIASES: Record<string, readonly string[]> = {
  accept: ["approve", "confirm"],
  add: ["new", "create", "plus"],
  delete: ["remove"],
  denied: ["rejected", "blocked"],
  download: ["save"],
  edit: ["update", "modify"],
  empty: ["blank", "no-results"],
  find: ["search", "lookup"],
  group: ["team"],
  internet: ["web", "online"],
  login: ["signin", "sign-in"],
  logout: ["signout", "sign-out"],
  lookup: ["search", "find"],
  mobile: ["phone", "smartphone"],
  modify: ["edit", "update"],
  online: ["web", "internet"],
  phone: ["mobile", "smartphone"],
  remove: ["delete"],
  search: ["find", "lookup"],
  signin: ["login", "sign-in"],
  "sign-in": ["login", "signin"],
  signout: ["logout", "sign-out"],
  "sign-out": ["logout", "signout"],
  smartphone: ["mobile", "phone"],
  team: ["group", "collaboration"],
  update: ["edit", "modify"],
  upload: ["import"],
  web: ["online", "internet"],
};
